### ISSUE TITLE
ValueError: Unknown CURIE prefix: file

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/BioPortal-to-KGX#13]
As of fc140ce1aa7d71506edd316977fdc37ad78a4517, the transform for `CANONT_1` proceeds like this:
```
ROBOT: relax CANONT_1
Relaxing /tmp/tmpln0gf78b to transformed/ontologies/CANONT/CANONT_1_relaxed.json...
Complete.
KGX transform CANONT_1
[KGX][cli_utils.py][    transform_source] INFO: Processing source 'CANONT_1_relaxed.json'
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    run()
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 28, in run
    do_transforms(data_filepaths)
  File "/home/harry/BioPortal-to-KGX/bioportal_to_kgx/functions.py", line 119, in do_transforms
    kgx.cli.transform(inputs=[relaxed_outpath],
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/cli/cli_utils.py", line 586, in transform
    transform_source(
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/cli/cli_utils.py", line 895, in transform_source
    transformer.transform(input_args, output_args)
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/transformer.py", line 247, in transform
    self.process(source_generator, intermediate_sink)
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/transformer.py", line 343, in process
    for rec in source:
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 62, in parse
    yield from chain(n, e)
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 86, in read_nodes
    yield self.read_node(n)
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 124, in read_node
    category = self.get_category(curie, node)
  File "/home/harry/kg-env/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 256, in get_category
    element = self.toolkit.get_element_by_mapping(category)
  File "/home/harry/kg-env/lib/python3.8/site-packages/bmt/toolkit.py", line 1057, in get_element_by_mapping
    mappings = self.get_all_elements_by_mapping(identifier)
  File "/home/harry/kg-env/lib/python3.8/site-packages/bmt/toolkit.py", line 1274, in get_all_elements_by_mapping
    self.generator.namespaces.uri_for(identifier), set()
  File "/home/harry/kg-env/lib/python3.8/site-packages/linkml_runtime/utils/namespaces.py", line 183, in uri_for
    raise ValueError(f"{TypedNode.yaml_loc(uri_or_curie)}Unknown CURIE prefix: {prefix}")
ValueError: Unknown CURIE prefix: file
```

This is unhandled and causes the set of transforms to fail.
The issue is local file references (mistakenly) included in the ontology. In the obojson they look like this:
```
...
"id" : "http://purl.obolibrary.org/obo/ID_0000052",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasOBONamespace",
          "val" : "file:C:/Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo"
        }
...
```

Easy solution is to catch the ValueError and skip this transform.
Assigning a namespace could fix the issue but seems to be outside the scope of a transform.

See also https://bioportal.bioontology.org/ontologies/CANONT/?p=classes&conceptid=root

**Comment by caufieldjh** [comment]
The broader issue here is that the `id` field above has a very generic name of `ID_0000052` - this is something OBO-Edit did, so likely won't be a problem for more recently updated ontologies, but does present some possibility of id collision.
