### ISSUE TITLE
ROBOT preprocessing fails due to null value

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/BioPortal-to-KGX#15]
The ROBOT relax fails because of the following error when parsing `DOID_617`:
```
ROBOT encountered an error:

  RAN: /home/harry/BioPortal-to-KGX/robot relax --input /tmp/tmpq3t8cyv0 --output transformed/ontologies/DOID/DOID_617_relaxed.json --vvv

  STDOUT:
2022-03-07 14:01:21,081 DEBUG org.obolibrary.robot.IOHelper - Loading ontology /tmp/tmpq3t8cyv0 with catalog file null
2022-03-07 14:01:21,082 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
2022-03-07 14:01:21,083 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/home/harry/BioPortal-to-KGX/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
2022-03-07 14:01:21,083 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/home/harry/BioPortal-to-KGX/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
2022-03-07 14:01:21,083 DEBUG org.semanticweb.owlapi... (24347 more, please see e.stdout)

  STDERR:
java.lang.NullPointerException: Cannot invoke "String.toString()" because "lv" is null
        at org.geneontology.obographs.owlapi.FromOwl.generateGraph(FromOwl.java:409)
        at org.geneontology.obographs.owlapi.FromOwl.generateGraphDocument(FromOwl.java:63)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1684)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
        at org.obolibrary.robot.RelaxCommand.execute(RelaxCommand.java:113)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
        at org.obolibrary.robot.CommandManager.main(CommandMa... (97 more, please see e.stderr)
ROBOT relax of DOID_617 failed - skipping.
```

The next transform continues as expected, but DOID doesn't get transformed.

**Comment by caufieldjh** [comment]
This also happens with `NIFSTD_27`

**Comment by caufieldjh** [comment]
I think the error starts here in `obographs`:
https://github.com/geneontology/obographs/blob/1a892a802dfb362018a7deea879ce75b54bbb563/obographs-owlapi/src/main/java/org/geneontology/obographs/owlapi/FromOwl.java#L410-L413

suggesting that lv is null in a comment in the source triples.
(and maybe this block should be preceded by `if (lv != null)`)

**Comment by caufieldjh** [comment]
Tried this but the output seemed to be missing too much content:
```
robot remove -vvv --input e67d70df45f6f4cc5b70b1296091 --axioms annotation --output DOID_617_fixed.json
```

Including `--trim false` raised a similar error as before:
```
robot remove -vvv --input e67d70df45f6f4cc5b70b1296091 --axioms annotation --trim false --output DOID_617_fixed.json
...
OBO GRAPH ERROR Could not convert ontology to OBO Graph (see https://github.com/geneontology/obographs)
For details see: http://robot.obolibrary.org/errors#obo-graph-error
java.io.IOException: errors#OBO GRAPH ERROR Could not convert ontology to OBO Graph (see https://github.com/geneontology/obographs)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1720)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:846)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:667)
        at org.obolibrary.robot.RemoveCommand.execute(RemoveCommand.java:202)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

Alternate option: http://robot.obolibrary.org/query#sparql-update
Other alternate: just parse the file and remove offending lines with a regex prior to `robot relax`

**Comment by caufieldjh** [comment]
This should work:
```
robot remove -vvv --input e67d70df45f6f4cc5b70b1296091 --term rdfs:comment --output DOID_617_fixed.json
```
