### ISSUE TITLE
Resolve transforms failing due to `Unknown CURIE prefix: file`

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/BioPortal-to-KGX#23]
Seven ontologies do not transform to KGX TSV due to presence of a value resembling a CURIE with a `file` prefix.
These are otherwise valid, if somewhat less-than-descriptive, values, and may be modified to permit the transform to continue.

**Comment by caufieldjh** [comment]
See https://github.com/ncbo/BioPortal-to-KGX/issues/22#issuecomment-1068382948 for all ontologies with this issue.

**Comment by caufieldjh** [comment]
A related issue appears to have popped up:
```
KGX transform CANONT_1
Encountered error during KGX transform of CANONT_1: Unknown CURIE prefix: file
Will attempt to repair file and try again.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab//Documents and Settings/Andre/My Documents/OBO/Ontology_Scholastic.obo does not look like a valid URI, trying to serialize this will break.
Normalizing graph...
Found these graph files:['transformed/ontologies/CANONT/CANONT_1_edges.tsv', 'transformed/ontologies/CANONT/CANONT_1_nodes.tsv']
Retrieving entity names in transformed/ontologies/CANONT/CANONT_1_nodes.tsv...
Traceback (most recent call last):
  File "/home/harry/BioPortal-to-KGX/run.py", line 138, in <module>
    run()
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/BioPortal-to-KGX/run.py", line 113, in run
    transform_status = do_transforms(
  File "/home/harry/BioPortal-to-KGX/bioportal_to_kgx/functions.py", line 345, in do_transforms
    if not clean_and_normalize_graph(filepath=outdir,
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/universalizer/norm.py", line 86, in clean_and_normalize_graph
    remap_these_nodes = make_id_maps(nodepath,
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/universalizer/norm.py", line 242, in make_id_maps
    assert curie_converter.expand(identifier)
  File "/home/harry/.cache/pypoetry/virtualenvs/bioportal-to-kgx-BG6p1jeu-py3.9/lib/python3.9/site-packages/curies/api.py", line 271, in expand
    prefix, identifier = curie.split(self.delimiter, 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

tl:dr the fix leaves something that can't be resolved to CURIE parts
